test: test.cc
	g++ -o test `pkg-config --cflags playerc++` test.cc `pkg-config --libs playerc++`

beebleboxrobot: beebleboxrobot.cc
	g++ -o beebleboxrobot `pkg-config --cflags playerc++` beebleboxrobot.cc `pkg-config --libs playerc++`

clean: 
	rm test
